/*
Deployment script for LibraryWebApp

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "LibraryWebApp"
:setvar DefaultFilePrefix "LibraryWebApp"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Foreign Key unnamed constraint on [dbo].[Author]...';


GO
ALTER TABLE [dbo].[Author] DROP CONSTRAINT [FK__Author__BirthLoc__32E0915F];


GO
PRINT N'Dropping Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] DROP CONSTRAINT [FK__Books__Author__33D4B598];


GO
PRINT N'Dropping Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] DROP CONSTRAINT [FK__Books__Genre__34C8D9D1];


GO
PRINT N'Dropping Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] DROP CONSTRAINT [FK__Books__Publisher__35BCFE0A];


GO
PRINT N'Dropping Foreign Key unnamed constraint on [dbo].[Publisher]...';


GO
ALTER TABLE [dbo].[Publisher] DROP CONSTRAINT [FK__Publisher__Birth__36B12243];


GO
PRINT N'Dropping Foreign Key unnamed constraint on [dbo].[User]...';


GO
ALTER TABLE [dbo].[User] DROP CONSTRAINT [FK__User__Role__37A5467C];


GO
PRINT N'Starting rebuilding table [dbo].[Author]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Author] (
    [AuthorId]      INT           IDENTITY (1, 1) NOT NULL,
    [FirstName]     VARCHAR (50)  NOT NULL,
    [LastName]      VARCHAR (50)  NULL,
    [DateOfBirth]   DATE          NOT NULL,
    [BirthLocation] INT           NULL,
    [Bio]           VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([AuthorId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Author])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Author] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Author] ([AuthorId], [FirstName], [LastName], [DateOfBirth], [BirthLocation], [Bio])
        SELECT   [AuthorId],
                 [FirstName],
                 [LastName],
                 [DateOfBirth],
                 [BirthLocation],
                 [Bio]
        FROM     [dbo].[Author]
        ORDER BY [AuthorId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Author] OFF;
    END

DROP TABLE [dbo].[Author];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Author]', N'Author';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Starting rebuilding table [dbo].[Books]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Books] (
    [BookId]      INT           IDENTITY (1, 1) NOT NULL,
    [Title]       VARCHAR (50)  NOT NULL,
    [Description] VARCHAR (250) NOT NULL,
    [IsPaperBack] BIT           NOT NULL,
    [PublishDate] DATE          NOT NULL,
    [Author]      INT           NOT NULL,
    [Genre]       INT           NOT NULL,
    [Publisher]   INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([BookId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Books])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Books] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Books] ([BookId], [Title], [Description], [IsPaperBack], [PublishDate], [Author], [Genre], [Publisher])
        SELECT   [BookId],
                 [Title],
                 [Description],
                 [IsPaperBack],
                 [PublishDate],
                 [Author],
                 [Genre],
                 [Publisher]
        FROM     [dbo].[Books]
        ORDER BY [BookId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Books] OFF;
    END

DROP TABLE [dbo].[Books];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Books]', N'Books';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Starting rebuilding table [dbo].[Genre]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Genre] (
    [GenreId]     INT           IDENTITY (1, 1) NOT NULL,
    [Name]        VARCHAR (50)  NOT NULL,
    [Description] VARCHAR (250) NULL,
    [IsFiction]   BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([GenreId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Genre])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Genre] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Genre] ([GenreId], [Name], [Description], [IsFiction])
        SELECT   [GenreId],
                 [Name],
                 [Description],
                 [IsFiction]
        FROM     [dbo].[Genre]
        ORDER BY [GenreId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Genre] OFF;
    END

DROP TABLE [dbo].[Genre];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Genre]', N'Genre';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Starting rebuilding table [dbo].[Publisher]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Publisher] (
    [PublisherId]   INT          IDENTITY (1, 1) NOT NULL,
    [Name]          VARCHAR (50) NULL,
    [BirthLocation] INT          NULL,
    PRIMARY KEY CLUSTERED ([PublisherId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Publisher])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Publisher] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Publisher] ([PublisherId], [Name], [BirthLocation])
        SELECT   [PublisherId],
                 [Name],
                 [BirthLocation]
        FROM     [dbo].[Publisher]
        ORDER BY [PublisherId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Publisher] OFF;
    END

DROP TABLE [dbo].[Publisher];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Publisher]', N'Publisher';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Starting rebuilding table [dbo].[Role]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Role] (
    [RoleId]   INT          IDENTITY (1, 1) NOT NULL,
    [RoleName] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([RoleId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Role])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Role] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Role] ([RoleId], [RoleName])
        SELECT   [RoleId],
                 [RoleName]
        FROM     [dbo].[Role]
        ORDER BY [RoleId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Role] OFF;
    END

DROP TABLE [dbo].[Role];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Role]', N'Role';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Starting rebuilding table [dbo].[User]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_User] (
    [UserId]    INT           IDENTITY (1, 1) NOT NULL,
    [Role]      INT           NOT NULL,
    [FirstName] CHAR (25)     NOT NULL,
    [LastName]  CHAR (25)     NOT NULL,
    [UserName]  CHAR (25)     NOT NULL,
    [Email]     CHAR (50)     NOT NULL,
    [Password]  VARCHAR (MAX) NOT NULL,
    [Salt]      VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[User])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_User] ON;
        INSERT INTO [dbo].[tmp_ms_xx_User] ([UserId], [Role], [FirstName], [LastName], [UserName], [Email], [Password], [Salt])
        SELECT   [UserId],
                 [Role],
                 [FirstName],
                 [LastName],
                 [UserName],
                 [Email],
                 [Password],
                 [Salt]
        FROM     [dbo].[User]
        ORDER BY [UserId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_User] OFF;
    END

DROP TABLE [dbo].[User];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_User]', N'User';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Author]...';


GO
ALTER TABLE [dbo].[Author] WITH NOCHECK
    ADD FOREIGN KEY ([BirthLocation]) REFERENCES [dbo].[Address] ([AddressId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] WITH NOCHECK
    ADD FOREIGN KEY ([Author]) REFERENCES [dbo].[Author] ([AuthorId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] WITH NOCHECK
    ADD FOREIGN KEY ([Genre]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] WITH NOCHECK
    ADD FOREIGN KEY ([Publisher]) REFERENCES [dbo].[Publisher] ([PublisherId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Publisher]...';


GO
ALTER TABLE [dbo].[Publisher] WITH NOCHECK
    ADD FOREIGN KEY ([BirthLocation]) REFERENCES [dbo].[Address] ([AddressId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[User]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD FOREIGN KEY ([Role]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.Author'), OBJECT_ID(N'dbo.Books'), OBJECT_ID(N'dbo.Publisher'), OBJECT_ID(N'dbo.User'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
