/*
Deployment script for LibraryWebApp

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "LibraryWebApp"
:setvar DefaultFilePrefix "LibraryWebApp"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Address]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[Address] (
    [AddressId] INT          NOT NULL,
    [Address]   VARCHAR (50) NOT NULL,
    [City]      VARCHAR (50) NOT NULL,
    [Country]   VARCHAR (50) NOT NULL,
    [State]     VARCHAR (2)  NULL,
    [Zip]       VARCHAR (5)  NULL,
    PRIMARY KEY CLUSTERED ([AddressId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Table [dbo].[Author]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[Author] (
    [AuthorId]      INT           NOT NULL,
    [FirstName]     VARCHAR (50)  NOT NULL,
    [LastName]      VARCHAR (50)  NULL,
    [DateOfBirth]   DATE          NOT NULL,
    [BirthLocation] INT           NULL,
    [Bio]           VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([AuthorId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Table [dbo].[Books]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[Books] (
    [BookId]      INT           NOT NULL,
    [Title]       VARCHAR (50)  NOT NULL,
    [Description] VARCHAR (250) NOT NULL,
    [IsPaperBack] BIT           NOT NULL,
    [PublishDate] DATE          NOT NULL,
    [Author]      INT           NOT NULL,
    [Genre]       INT           NOT NULL,
    [Publisher]   INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([BookId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Table [dbo].[Genre]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[Genre] (
    [GenreId]     INT           NOT NULL,
    [Name]        VARCHAR (50)  NOT NULL,
    [Description] VARCHAR (250) NULL,
    [IsFiction]   BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([GenreId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Table [dbo].[Publisher]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[Publisher] (
    [PublisherId]   INT          NOT NULL,
    [Name]          VARCHAR (50) NULL,
    [BirthLocation] INT          NULL,
    PRIMARY KEY CLUSTERED ([PublisherId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Table [dbo].[Role]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[Role] (
    [RoleId]   INT          NOT NULL,
    [RoleName] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([RoleId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Table [dbo].[User]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [dbo].[User] (
    [UserId]    INT           NOT NULL,
    [Role]      INT           NOT NULL,
    [FirstName] CHAR (25)     NOT NULL,
    [LastName]  CHAR (25)     NOT NULL,
    [UserName]  CHAR (25)     NOT NULL,
    [Email]     CHAR (50)     NOT NULL,
    [Password]  VARCHAR (MAX) NOT NULL,
    [Salt]      VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Author]...';


GO
ALTER TABLE [dbo].[Author] WITH NOCHECK
    ADD FOREIGN KEY ([BirthLocation]) REFERENCES [dbo].[Address] ([AddressId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] WITH NOCHECK
    ADD FOREIGN KEY ([Author]) REFERENCES [dbo].[Author] ([AuthorId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] WITH NOCHECK
    ADD FOREIGN KEY ([Genre]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Books]...';


GO
ALTER TABLE [dbo].[Books] WITH NOCHECK
    ADD FOREIGN KEY ([Publisher]) REFERENCES [dbo].[Publisher] ([PublisherId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Publisher]...';


GO
ALTER TABLE [dbo].[Publisher] WITH NOCHECK
    ADD FOREIGN KEY ([BirthLocation]) REFERENCES [dbo].[Address] ([AddressId]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[User]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD FOREIGN KEY ([Role]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating View [dbo].[Register]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE VIEW [dbo].[Register]
	AS SELECT * FROM [User]
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.Author'), OBJECT_ID(N'dbo.Books'), OBJECT_ID(N'dbo.Publisher'), OBJECT_ID(N'dbo.User'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
